### -Indexing

In [1]:
#make a string
a = "Samaosa Pakora"
a

'Samaosa Pakora'

In [2]:
#length of indexces

len(a)

14

In [3]:
a[0]

'S'

In [4]:
a[1]

'a'

In [5]:
a[13]

'a'

In [6]:
a[6:8]

'a '

In [7]:
a[-3]

'o'

In [8]:
a[-8:-3]

'a Pak'

In [9]:
food = "biryani"
food

'biryani'

### - String Method

In [10]:
len(food)

7

In [11]:
food.capitalize()

'Biryani'

In [12]:
food.upper()

'BIRYANI'

In [13]:
food.lower()

'biryani'

In [14]:
food.replace('b', "Sh")

'Shiryani'

In [15]:
#counting a specifc alphabat with python
name = "Muhammad Usman with Bba Ammar Tufail"
name

'Muhammad Usman with Bba Ammar Tufail'

In [16]:
name.count("a")

6

### - Finding an index number in string

In [17]:
name.find("T")

30

In [18]:
#How to split a string
food = ["I love samosa, pakora, raita, biryani and karahi"]
food

['I love samosa, pakora, raita, biryani and karahi']

### -Basic data structures in python
1 -Tuples
2 -List
3 -Dictionaries
4 -Set

### -Tuple
- ordered collection of element
- enclosed in round() braces paranthesis
- Diffrent type of element can be stored
- once the element stored you cannot change them

In [19]:
tup_1 = (1, "Python", True, 2.5)
tup_1

(1, 'Python', True, 2.5)

In [20]:
#Type of tuple
type(tup_1)


tuple

### -Indexing in tuples

In [21]:
tup_1[1]

'Python'

In [22]:
tup_1[0:3]

(1, 'Python', True)

In [23]:
tup_1[-3:-1]

('Python', True)

In [24]:
#counting of element
len(tup_1)

4

In [25]:
tup_2 = (2, "MuhammadUsman", 3.5, False)
tup_2

(2, 'MuhammadUsman', 3.5, False)

In [26]:
tup_1 + tup_2

(1, 'Python', True, 2.5, 2, 'MuhammadUsman', 3.5, False)

tup_1*2 + tup_2

In [27]:
tup_3 = (20, 25, 30, 56, 86, 78, 100)
tup_3

(20, 25, 30, 56, 86, 78, 100)

In [28]:
#minimum value of tuple
min(tup_3)

20

In [29]:
#maximum value of tuple
max(tup_3)

100

In [30]:
tup_3*2

(20, 25, 30, 56, 86, 78, 100, 20, 25, 30, 56, 86, 78, 100)

### -List

- ordered collection of element 
- enclosed in squar[] braces paranthesis 
- once the element stored you can change them muteable

In [31]:
List_1 = [2, "MuhammadUsman", False]
List_1

[2, 'MuhammadUsman', False]

In [32]:
#Type of list
type(List_1)


list

In [33]:
#Length of list
len(List_1)

3

In [34]:
List_1[2]

False

In [35]:
List_2 = [2, 4, "Usman", "Khalid", 3.6, False]
List_2

[2, 4, 'Usman', 'Khalid', 3.6, False]

In [36]:
List_1 + List_2


[2, 'MuhammadUsman', False, 2, 4, 'Usman', 'Khalid', 3.6, False]

In [37]:
List_2*3

[2,
 4,
 'Usman',
 'Khalid',
 3.6,
 False,
 2,
 4,
 'Usman',
 'Khalid',
 3.6,
 False,
 2,
 4,
 'Usman',
 'Khalid',
 3.6,
 False]

In [38]:
List_1.reverse()

In [39]:
List_1

[False, 'MuhammadUsman', 2]

In [40]:
List_1.append("Wellcome")

In [41]:
List_1

[False, 'MuhammadUsman', 2, 'Wellcome']

In [42]:
#Count the element you enter 
List_1.count(False)

1

In [43]:
List_3 = [12, 34, 56, 78, 36, 32, 57, 112, 93, 45, 23, 13, 100, 998]
List_3

[12, 34, 56, 78, 36, 32, 57, 112, 93, 45, 23, 13, 100, 998]

In [44]:
List_3.sort()
List_3

[12, 13, 23, 32, 34, 36, 45, 56, 57, 78, 93, 100, 112, 998]

### -Dictionaries 
- An unordered collection of data
- Key and value
- curly braces{}
- Mutatable, changable

In [45]:
#Food and their prices
Dic_1 = {"samosa": 30, "Pakora": 100, "Raita": 20, "Salad": 50, "Chiken Roll": 40}
Dic_1

{'samosa': 30, 'Pakora': 100, 'Raita': 20, 'Salad': 50, 'Chiken Roll': 40}

In [46]:
type(Dic_1)

dict

In [47]:
Keys_1 = Dic_1.keys()
Keys_1

dict_keys(['samosa', 'Pakora', 'Raita', 'Salad', 'Chiken Roll'])

In [48]:
Values_1 = Dic_1.values()
Values_1

dict_values([30, 100, 20, 50, 40])

In [49]:
#adding new element (Mutatable)
Dic_1["Tikki"] = 10
Dic_1

{'samosa': 30,
 'Pakora': 100,
 'Raita': 20,
 'Salad': 50,
 'Chiken Roll': 40,
 'Tikki': 10}

In [50]:
#update the values 
Dic_1['Tikki'] = 15
Dic_1

{'samosa': 30,
 'Pakora': 100,
 'Raita': 20,
 'Salad': 50,
 'Chiken Roll': 40,
 'Tikki': 15}

In [51]:
Dic_2 = {"Dates": 50, "choclates": 200, "Saweeya": 1000}
Dic_2

{'Dates': 50, 'choclates': 200, 'Saweeya': 1000}

In [52]:
#Concacinate Disctionaries
Dic_1.update(Dic_2)

In [53]:
Dic_1

{'samosa': 30,
 'Pakora': 100,
 'Raita': 20,
 'Salad': 50,
 'Chiken Roll': 40,
 'Tikki': 15,
 'Dates': 50,
 'choclates': 200,
 'Saweeya': 1000}

### -Sets
- Unordered and unindexed 
- Curly braces {}
- No dublicates allowed

In [54]:
s_1 = {1, 2.3, 5.5, "Usman", "Huzaifa", "Ammar", True}
s_1

{1, 2.3, 5.5, 'Ammar', 'Huzaifa', 'Usman'}

In [55]:
s_1.add("Ammar1")
s_1

{1, 2.3, 5.5, 'Ammar', 'Ammar1', 'Huzaifa', 'Usman'}

In [56]:
s_1.remove("Ammar1")
s_1

{1, 2.3, 5.5, 'Ammar', 'Huzaifa', 'Usman'}

In [57]:
s_2 = {2.4, "Ali"}
s_1.union(s_2)

{1, 2.3, 2.4, 5.5, 'Ali', 'Ammar', 'Huzaifa', 'Usman'}

### -Array

In [58]:
import numpy as np
a = np.array([2, 3, 5])
a

array([2, 3, 5])

In [59]:
type(a)

numpy.ndarray

In [60]:
#indexing
a[2]

5

In [61]:
a[1:3]

array([3, 5])

In [62]:
len(a)

3

### -2D-Array

In [63]:
#list of lists
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
len(arr)


3

In [65]:
type(arr)

numpy.ndarray

In [66]:
arr[0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
zero_2 = np.zeros((2,4))
zero_2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
zero_1 = np.zeros(3)
zero_1

array([0., 0., 0.])

In [69]:
ones_1 = np.ones(2)
ones_1

array([1., 1.])

In [70]:
empty_1 = np.empty(7)
empty_1

array([0., 0., 0., 0., 0., 0., 0.])

In [71]:
#array with range of element
ran = np.arange(5)
ran

array([0, 1, 2, 3, 4])

In [72]:
#array with specific number of element
spe = np.arange(2, 13)
spe

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
#continue
con = np.arange(2, 25, 3)
con

array([ 2,  5,  8, 11, 14, 17, 20, 23])

In [74]:
#linear spaced number
lin = np.linspace(2, 15, num=5)
lin


array([ 2.  ,  5.25,  8.5 , 11.75, 15.  ])

In [75]:
#specific data type in array
data_1 = np.ones(5, dtype = np.int8)
data_1

array([1, 1, 1, 1, 1], dtype=int8)

In [76]:
#specific data type in array
data_2 = np.ones(3, dtype = np.float64)
data_2

array([1., 1., 1.])

In [77]:
#making and reshaping 3d array
arr_3D = np.arange(40).reshape(2, 4, 5)
arr_3D

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])