In [1]:
#first import numpy library
import numpy as np

### - Creating an array with numpy

In [10]:
# 1-D Array
food_1 = np.array(["Samosa", "Pakora", "Salad"])
food_1

array(['Samosa', 'Pakora', 'Salad'], dtype='<U6')

In [8]:
price_1 = np.array([5, 2, 10])
price_1

array([ 5,  2, 10])

In [9]:
price_1.mean()

5.666666666666667

### - Array functions 

In [12]:
arr_1 = np.array([14, 12, 74, 0.3, 12.9, 13, 100, 73, 1.9, 45])
arr_1

array([ 14. ,  12. ,  74. ,   0.3,  12.9,  13. , 100. ,  73. ,   1.9,
        45. ])

In [17]:
arr_1.sort()
arr_1

array([  0.3,   1.9,  12. ,  12.9,  13. ,  14. ,  45. ,  73. ,  74. ,
       100. ])

In [18]:
arr_2 = np.array([12, 12.5, 45, 23, 10, 10.3, 2.4])
arr_2

array([12. , 12.5, 45. , 23. , 10. , 10.3,  2.4])

In [24]:
concat_1 = np.concatenate((arr_1 , arr_2))
concat_1

array([  0.3,   1.9,  12. ,  12.9,  13. ,  14. ,  45. ,  73. ,  74. ,
       100. ,  12. ,  12.5,  45. ,  23. ,  10. ,  10.3,   2.4])

In [25]:
concat_1.sort()
concat_1

array([  0.3,   1.9,   2.4,  10. ,  10.3,  12. ,  12. ,  12.5,  12.9,
        13. ,  14. ,  23. ,  45. ,  45. ,  73. ,  74. , 100. ])

In [27]:
arr_2D_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2D_1

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr_2D_2 = np.array([[10, 11, 12], [13, 14, 15]])
arr_2D_2

array([[10, 11, 12],
       [13, 14, 15]])

In [37]:
np.concatenate((arr_2D_1, arr_2D_2),  axis= 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12],
       [13, 14, 15]])

In [38]:
np.concatenate((arr_2D_1, arr_2D_2),  axis= 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15]])

In [39]:
arr_3D_1 = np.array([[[0, 1, 2, 3],
                    [4, 5, 6, 7]],
                     
                    [[8, 9, 10, 11],
                    [12, 13, 14, 15]],
                     
                    [[16, 17, 18, 19],
                    [20, 21, 22, 23]]])
arr_3D_1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [40]:
#to find the dimensions of array
arr_3D_1.ndim

3

In [41]:
#to find the size of array
arr_3D_1.size

24

In [43]:
#to find the shape of array
arr_3D_1.shape

(3, 2, 4)

In [49]:
arr_3D_2 = np.arange(24)
arr_3D_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
arr_3D_2.reshape(3,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])