In [1]:
#first import numpy library
import numpy as np

In [2]:
a1 = np.arange(6)
a1

array([0, 1, 2, 3, 4, 5])

In [3]:
a2 = a1[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [4]:
a2.shape

(1, 6)

In [5]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[1]

array([5, 6, 7, 8])

In [6]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[0][2]

3

In [7]:
np.reshape(a, newshape=(1, 12), order='C')


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])